# Generated by Django 5.2.13 on 2026-05-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_chapter_unique_together_remove_chapter_course_and_more'),
        ('nests', '0002_nest_status_nestmembership_alter_nest_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='nest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='nests.nest'),
        ),
    ]
