# Generated by Django 5.2.13 on 2026-05-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='NestMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('assistant', 'Assistant'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='nests.nest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nest_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nest', 'joined_at'],
            },
        ),
        migrations.AlterField(
            model_name='nest',
            name='members',
            field=models.ManyToManyField(related_name='nests', through='nests.NestMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nestmembership',
            constraint=models.UniqueConstraint(fields=('nest', 'user'), name='unique_nest_membership'),
        ),
    ]
