# Generated by Django 5.2.13 on 2026-05-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nests', '0002_nest_status_nestmembership_alter_nest_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NestRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(choices=[('New Member', 'New Member'), ('Explorer', 'Explorer'), ('Contributor', 'Contributor'), ('Active Contributor', 'Active Contributor'), ('Engaged Member', 'Engaged Member'), ('Top Contributor', 'Top Contributor'), ('Advanced Contributor', 'Advanced Contributor'), ('Core Member', 'Core Member'), ('Mentor', 'Mentor'), ('Senior Mentor', 'Senior Mentor'), ('Knowledge Leader', 'Knowledge Leader'), ('Nest Expert', 'Nest Expert'), ('Master Contributor', 'Master Contributor'), ('Pillar of the Nest', 'Pillar of the Nest')], default='New Member', max_length=64)),
                ('badge', models.CharField(blank=True, choices=[('', '—'), ('First Responder', 'First Responder'), ('Rapid Helper', 'Rapid Helper'), ('Problem Solver', 'Problem Solver'), ('Verified Expert', 'Verified Expert'), ('Precision Thinker', 'Precision Thinker'), ('Curious Mind', 'Curious Mind'), ('Explorer', 'Explorer'), ('Collaborator', 'Collaborator'), ('Discussion Starter', 'Discussion Starter'), ('Community Builder', 'Community Builder'), ('Influencer', 'Influencer'), ('Insightful Voice', 'Insightful Voice')], default='', max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='nests.nest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'nest')},
            },
        ),
    ]
