# Generated by Django 5.2.13 on 2026-05-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_created_by_submission_student'),
        ('nests', '0002_nest_status_nestmembership_alter_nest_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='nest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='nests.nest'),
        ),
    ]
