# Generated by Django 5.2.13 on 2026-05-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_nest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text Answer')], max_length=20),
        ),
    ]
