# Generated by Django 5.2.13 on 2026-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes (0 = no time limit)'),
        ),
    ]
