# Generated by Django 5.2.13 on 2026-05-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_duration'),
        ('assessments', '0005_assessment_duration'),
    ]

    operations = [
    ]
