# Generated by Django 5.2.13 on 2026-04-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='details',
            new_name='detail',
        ),
    ]
